export * from './mongo'
export * from './advices'
export * from './drugs'
export * from './diseases'
export * from './auth'
export * from './diagnoses'
export * from './patients'
export * from './doctors'