export * from './advices.schema'
export * from './admins.schema'
export * from './diseases.schema'
export * from './doctors.schema'
export * from './drugs.schema'
export * from './diagnosis.schema'
export * from './patients.schema'