export * from './advices.schema'
export * from './diagnosis-statistics.schema'
export * from './disease-advice.schema'
export * from './disease-drug.schema'
export * from './diseases.schema'
export * from './doctors.schema'
export * from './drugs.schema'
export * from './patient.schema'